### ISSUE TITLE
地図情報が多すぎてGISで使用しづらい

### ISSUE THREAD

**Issue by tmizu23** [gsi-cyberjapan/experimental_wmts#1]
GISでWMTSを読み込むと、すべての地図タイル一覧が表示され、使用したい地図を見つけにくい。
また、地図一覧のロードにも時間がかかっている。

標準地図、空中写真など、一般的なユーザーにとって使用頻度が高いと思われるものだけのWMTSも提供してもらいたい。

**Comment by johofukyu** [comment]
ご意見ありがとうございます。
地理院地図の背景地図（標準地図、淡色地図、白地図、English、写真）のみの軽量版を作成しました。

http://gsi-cyberjapan.github.io/experimental_wmts/gsitiles_wmts_light.xml

**Comment by tmizu23** [comment]
早々のご対応ありがとうございます！
